FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN apt update && apt install -y git
COPY src/netlify /usr/src/app/src/netlify
COPY tests/connect-netlify/app /usr/src/app/tests/connect-netlify/app
WORKDIR /usr/src/app/tests/connect-netlify/app
RUN rm -rf node_modules && pnpm install 
CMD pnpm dev --no-open
