FROM node:22-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm install -g corepack@latest
RUN corepack enable
RUN apt update && apt install -y git
RUN git clone https://github.com/fireproof-storage/fireproof-ucan.git /usr/src/app
WORKDIR /usr/src/app
RUN pnpm --version
RUN pnpm i 
EXPOSE 8787
CMD pnpm run dev --ip 0.0.0.0
