FROM node:22-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm install -g corepack@latest
RUN corepack enable
RUN apt update && apt install -y git unzip curl python3 make g++
RUN curl -fsSL https://deno.land/install.sh | DENO_INSTALL=/usr/local sh && deno upgrade 1.46.3

COPY src /usr/src/app/src

WORKDIR /usr/src/app

RUN pnpm init && \
    pnpm install -g netlify netlify-cli json \
	--allow-build @parcel/watcher --allow-build esbuild \
	--allow-build netlify-cli --allow-build sharp \
	--allow-build unix-dgram && \
    pnpm add @netlify/blobs @netlify/functions && \
    json -I -f package.json -e 'this.type="module"'

CMD ["netlify","functions:serve","--functions","src/netlify/backend", "--port", "8888"]
