AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  fp-aws-backend

  Sample SAM Template for fp-aws-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MetaStoreTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: metaStore
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
        - AttributeName: cid
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
        - AttributeName: cid
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  UploadsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Environment:
        Variables:
          UploadBucket: "testbucket"
          AWS_ENDPOINT: "http://127.0.0.1:9000/"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: djkfdlsgadlsghgdummy
          AWS_SECRET_ACCESS_KEY: LdjfdfDSFKDSfdDfdkjdlfgkdgjdglgkaghdummy
          OVERRIDE_AWS_ACCESS_KEY_ID: "minioadmin"
          OVERRIDE_AWS_SECRET_ACCESS_KEY: "minioadmin"
      #          TABLE_NAME: !Ref MyDynamoDBTable
      CodeUri: ./
      Handler: app.handler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Events:
        GetUploads:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /uploads
            Method: get
        PutUploads:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /uploads
            Method: put
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UploadsApi:
    Description: "API Gateway endpoint URL for Prod stage for Uploads function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  UploadsFunction:
    Description: "Uploads Lambda Function ARN"
    Value: !GetAtt UploadsFunction.Arn
  UploadsFunctionIamRole:
    Description: "Implicit IAM Role created for Uploads function"
    Value: !GetAtt UploadsFunctionRole.Arn
