// Generated by Wrangler on Fri Aug 16 2024 13:55:06 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

import type { DurableObjectNamespace } from "@cloudflare/workers-types";
import { FPMetaGroups } from "./fp-meta-groups.js";
import { WSEvents } from "hono/ws";

export interface Env {
  // bucket: R2Bucket;
  // kv_store: KVNamespace;

  /** AWS/S3 access key ID for storage backend */
  ACCESS_KEY_ID: string;
  ACCOUNT_ID: string;
  BUCKET_NAME: string;
  CLOUDFLARE_API_TOKEN: string;
  EMAIL: string;
  FIREPROOF_SERVICE_PRIVATE_KEY: string;
  POSTMARK_TOKEN: string;
  SECRET_ACCESS_KEY: string;
  SERVICE_ID: string;
  STORAGE_URL: string;
  REGION: string;
  VERSION: string;
  FP_DEBUG: string;
  FP_STACK: string;
  FP_FORMAT: string;
  FP_PROTOCOL: string;
  /** Test date in ISO8601 format (YYYYMMDD'T'HHmmss'Z'). Optional. */
  TEST_DATE?: string;
  /** Maximum idle time in seconds before connection timeout. Optional. */
  MAX_IDLE_TIME?: string;

  FP_META_GROUPS: DurableObjectNamespace<FPMetaGroups>;

  WS_EVENTS: WSEvents;
}

// declare module "cloudflare:test" {
//   // ...or if you have an existing `Env` type...
//   interface ProvidedEnv extends Env {
//     readonly test: boolean;
//   }
// }
